name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # build artifact for ec2

      - name: install deps
        run: |
          cd backend
          npm ci

      - name: create artifact
        run: |
          cd backend
          tar -czf ../app.tar.gz .


      # copy artifact to ec2  ⭐ IMPORTANT
      - name: copy artifact
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: backend/app.tar.gz
          target: /tmp/

      # run deploy
      - name: deploy on ec2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/skincare/scripts
            chmod +x deploy.sh
            ./deploy.sh v$(date +%s)
