
name: ssh-test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: ssh into ec2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/skincare
            git fetch origin
            git reset --hard origin/main
            chmod +x scripts/deploy.sh
            cd scripts
            ./deploy.sh v$(date +%s)
